"""adds fields in user model

Revision ID: 710096eb32a6
Revises: 3812e025144c
Create Date: 2019-01-22 22:34:59.848120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710096eb32a6'
down_revision = '3812e025144c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
